[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pft-wallet"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "boto3",
    "dynaconf",
    "websockets",
    "web3",
    "click"
]

[tool.setuptools.package-data]
pft_wallet = ["static/**/*"]

[project.scripts]
pft-wallet = "pft_wallet.cli:main"

[tool.setuptools]
packages = ["pft_wallet"]
package-dir = {"" = "src"}